### ISSUE TITLE
Napkin Math on Storage Requirements

### ISSUE THREAD

**Issue by epugh** [o19s/opensearch-ubi#113]
A question that periodically comes up is about "how much data will this generate".   As my friend Simon likes to do, https://github.com/sirupsen/napkin-math, is come up with some rough numbers.

My gut is that the volume of data we collect isn't egregious because we aren't doing server logs.   A million SaaS products collect this data ;-).  And we have the power of OS to back us up.

I suspect this is a bit of a red herring concern:

> In talking to our Systems Architects, I find that they are very concerned about the data volumes (and therefore costs) for large users.
> My answer to this has been that the OS plugin is suitable for prototyping, experimentation, and smaller users.
Another part of the answer is that we are very good at scaling to large volumes of infrequently accessed data – perhaps the data is ingested into S3 for offline analysis, while only 24 hours are kept in live OpenSearch (if at all).

**Comment by jzonthemtn** [comment]
+1 to prioritizing the export to off load that data. Although, I'm not sure how much work there might actually be for us to do when there are a decent number of existing tools to dump. I think `elasticsearch-dump` can dump from OpenSearch to json files on S3, which can be queried using Amazon Athena or further imported into some other tool.

An example: 
[Copy data from Aiven for OpenSearch® to AWS S3 using elasticsearch-dump](https://aiven.io/docs/products/opensearch/howto/import-opensearch-data-elasticsearch-dump-to-aws)

**Comment by jzonthemtn** [comment]
Some preliminary numbers of storage:

queries index for 197743 queries: 45.4mb
events index for 196485 events: 4.1mb

Queries (right now) are significantly larger than events due to saving the raw query and the query response hits. I assume events themselves could be larger, and will also be more of them than queries. But maybe those numbers give a rough idea.

**Comment by jzonthemtn** [comment]
Related to #117. Not storing the full query would have significant impacts on the required storage space.

**Comment by jzonthemtn** [comment]
I'm going to close this issue because we have some rough estimates. The issue can be reopened or a new issue created if additional numbers are needed.
