### ISSUE TITLE
[META] User Behavior Insights Plan

### ISSUE THREAD

**Issue by epugh** [o19s/opensearch-ubi#125]
### Is your feature request related to a problem?
Meta issue to keep track of all the features and tasks in the scope of User Behavior Insights Framework.
As for now, there are multiple areas we want to invest to improve the understanding of users  in OpenSearch

## Targeting for 2.13.0
 * Capturing Server side Search events support for a single node OpenSearch.
 * Experimental Schema for user behavior events
 * Basic JavaScript client to capture said events on the front end
 * Documentation of how to query captured events in OpenSearch for specific data.
   * Personalization Data Feed
   * Interactive query: show table of query text, time stamp, result rank for purchases of Red Dress SKU9 .
 * Demonstration Kata using chorus-opensearch-edition

## Targeting for 2.14.0
 * Capturing Server side Search events support for multi node OpenSearch
 * Simulate 10,000 search sessions a day for six months.
 * Ship a basic JavaScript client as part of the UBI plugin distribution.
 * Ship a React Native client
 * Initial OpenSearch Dashboard for querying data
    * Searches without results
    * Trending searches
    * Lost opportunities
    * Rank histogram of conversions
 * First Cut of Standard Schema of Events

## Targeting for 2.15.0
 * UBI plugin is part of OpenSearch Project Github repo
 * More advanced Dashboard for querying data
    * ? What specifically?
    * ? What specifically ?

**Comment by jzonthemtn** [comment]
Closing because this appears to be satisfied with the exception of the dashboarding work.
