### ISSUE TITLE
Look at index naming for stores

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/opensearch-ubi#148]
For UBI stores, the indexes use the naming convention `.[store-name]_events` and `.[store-name]_queries`. This convention was chosen to follow the naming convention for a hidden index. There are now a few considerations we should look at:

* Our indexes are not actually created as hidden indexes. We should determine if they can/should be.
* Per the OpenSearch log: "in the next major version, index names starting with a dot are reserved for hidden indices and system indices." If our indexes are not actually hidden, we should change the name to follow the convention.
* We recently discovered that some OpenSearch SQL statements do not execute as expected due to the index names starting with a dot.

We should look at these considerations (and others?) and determine if we should adjust UBI's index naming convention.

**Comment by jzonthemtn** [comment]
My first thought is the indexes do not need to be hidden indexes, and we should change the naming convention to something like `ubi_[store-name]_queries` and `ubi_[store-name]_events`.

**Comment by epugh** [comment]
I think that if we can talk ourselves into this, then it makes it easier then fixing the SQL tool!    Do we envision more `ubi_[store-name]_[something_else]` at this point?   Would having a bunch matter?  what if we had hot and cold versions of the the `_queries` and `_events`, or did some sort of time based index naming, would that matter???

**Comment by jzonthemtn** [comment]
Right now, no, we don't have a need for other indexes. I don't think those other items matter, but it could be that we just don't have a use-case for others at this point.

I think it would be good to make a decision on this prior to a release for OpenSearch 2.13.0 to avoid having early users have to rename their UBI indexes at some point in the future.

**Comment by jzonthemtn** [comment]
Here is a [pull request](https://github.com/o19s/opensearch-ubi/pull/151) to change the naming to `ubi_[store-name]_events` and `ubi_[store-name]_queries`.

**Comment by jzonthemtn** [comment]
Closing as OBE.
