### ISSUE TITLE
Add a plugin unit test to validate the json event schema

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/opensearch-ubi#179]
Add a plugin unit test to validate the json event schema.

**Comment by jzonthemtn** [comment]
@epugh What did we want to validate the [schema ](https://raw.githubusercontent.com/o19s/ubi/main/schema/X.Y.Z/event.schema.json)against in the plugin? Against the `ubi_events` index mapping? Against samples of events?

**Comment by epugh** [comment]
I gave it some thought..    So, in a perfect world, where github.com/o19s/ubi was the focus, we might have some sort of "Technology Compatiblity Kit" (https://en.wikipedia.org/wiki/Technology_Compatibility_Kit) that you would take a stream of your event data and bounce it off UBI.   Imagine the `pandas.describe` where it tells you about the events that are compatible, but also the ones that are NOT.   Plus characteristics of the stream of events.    That would be powerful, and would properly live in the github.com/o19s/ubi repo.

Here...   I think what we want is a simple test that demonstrates "Here is a sample event" for opensearch and "here it passes the schema" and it is compatible with being indexed into opensearch.   We have this event file: https://github.com/o19s/ubi/blob/main/samples/event-opensearch.json, it isn't the best, it doesn't cover everything that the schema wants (I believe), but if we could update it to be more comprehensive, and have the test, I think that would be a great test.   I do think this is verging on integration test ;-).   This would validate our schema, validate the example event was still good, and ensure as we tweak/change both schema version and opensearch version that over time things remain compatible.

**Comment by epugh** [comment]
Would the same pattern make sense for queries?   Still need to populate https://github.com/o19s/ubi/blob/main/samples/query-opensearch.json ;-).

**Comment by jzonthemtn** [comment]
Re-created at https://github.com/opensearch-project/user-behavior-insights/issues/6e
