### ISSUE TITLE
Use a user-configurable ID for the search response document IDs

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/opensearch-ubi#67]
Currently, the `_id` is being used for the unique ID of each item in a search response. This ID has the risk of not being consistently unique. Instead of using the `_id`, we need to use a field that represents the item such as `sku`, `product_id`, or other identifier. 

What field is used needs to be configurable by the user. The name of the field can be provided during initialization of the store, such as `curl -X PUT localhost:9200/_plugins/ubi/{store}?id_field=sku`.

**Comment by epugh** [comment]
It would be nice if you skip this step that `_id` would be a fine default...  I can imagine plenty of places wehre `_id` is okay....

**Comment by jzonthemtn** [comment]
It can certainly be a default as long as we have the ability to let a different field be used.

**Comment by jzonthemtn** [comment]
A parameter will be added to the store initialization call to specify the name of the index the new store is associated with and the name of the uniquely identifying field, e.g.:

```
curl -X PUT http://localhost:9200/_plugins/ubi/mystore?index=ecommerce&field=sku
```

- If the `field` parameter is not provided, it will default to using `_id`. 
- The `index` parameter will be required. Right now we don't have an association between a store and an index - all queries are logged to the same store. Having an association between a store and an index will allow a single OpenSearch instance to have multiple UBI stores, each associated with a specific index.

**Comment by jzonthemtn** [comment]
Pull request #91 has information on how to walk through this change.
