### ISSUE TITLE
Make sure our schema allows for SQL joins across indices

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/opensearch-ubi#8]
Make sure our schema allows for SQL joins across indices.

**Comment by jzonthemtn** [comment]
We need to look at the initial list of desired reporting charts/graphs and ensure that our schemas can support the queries to power those visualizations.

**Comment by jzonthemtn** [comment]
We should mock up what each chart would look like and then try creating each one in OpenSearch Dashboards.

**Comment by RasonJ** [comment]
Reported the bug here: https://github.com/opensearch-project/sql/issues/2550
