### ISSUE TITLE
First Demo of Backend Query Showing User Behavior Insight

### ISSUE THREAD

**Issue by epugh** [o19s/opensearch-ubi#87]
@RasonJ I would really like this to be more specific.   @smacrakis has suggested recently top queries or top zero-result queries, though both of those *could* be done on the server side ;-).

**Comment by smacrakis** [comment]
I was trying to keep it simple....
What is more interesting is how to write queries which summarize more than one event, e.g., top queries with no clicks on results, or histogram of click rank.
